name: shrex
channels:
  - defaults
dependencies:
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - openssl=1.1.1s
  - pip=22.2.2
  - python=3.7.15
  - setuptools=65.5.0
  - sqlite=3.39.3
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.6
  - zlib=1.2.13
  - pip:
    - absl-py==1.3.0
    - ale-py==0.8.0
    - astor==0.8.1
    - astunparse==1.6.3
    - atari-py==0.2.9
    - attrs==22.1.0
    - autorom==0.4.2
    - autorom-accept-rom-license==0.4.2
    - cachetools==5.2.0
    - charset-normalizer==2.1.1
    - click==8.1.3
    - cloudpickle==2.2.0
    - cycler==0.11.0
    - dill==0.3.6
    - distro==1.8.0
    - exceptiongroup==1.0.4
    - flatbuffers==22.10.26
    - fonttools==4.38.0
    - gast==0.4.0
    - google-auth==2.14.1
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.50.0
    - gym==0.10.8
    - gym-notices==0.0.8
    - h5py==3.7.0
    - idna==3.4
    - importlib-metadata==5.0.0
    - importlib-resources==5.10.0
    - iniconfig==1.1.1
    - joblib==1.2.0
    - keras==2.10.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.4
    - libclang==14.0.6
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.5.3
    - numpy==1.21.6
    - oauthlib==3.2.2
    - opencv-python==4.6.0.66
    - opt-einsum==3.3.0
    - packaging==21.3
    - pillow==9.3.0
    - pluggy==1.0.0
    - progressbar2==4.2.0
    - protobuf==3.19.6
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyglet==1.5.27
    - pyopengl==3.1.6
    - pyparsing==3.0.9
    - pytest==7.2.0
    - python-dateutil==2.8.2
    - python-utils==3.4.5
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-build==0.16.2
    - scipy==1.7.3
    - six==1.16.0
    - tensorboard==1.14.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==1.14.0
    - tensorflow-estimator==1.14.0
    - tensorflow-io-gcs-filesystem==0.27.0
    - termcolor==2.1.0
    - tomli==2.0.1
    - torch==1.13.0
    - tqdm==4.64.1
    - typing-extensions==4.4.0
    - urllib3==1.26.12
    - werkzeug==2.2.2
    - wrapt==1.14.1
    - zipp==3.10.0
